version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - .:/home/node/api

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_data:/data/configdb
    networks:
      - backend_network

  redis:
    image: redis/redis-stack:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis:/data
    networks:
      - backend_network

volumes:
  myapi:
  mongo_data:
  redis:

networks:
  backend_network:
    driver: bridge
